DROP TABLE IF EXISTS Stores;
CREATE TABLE Stores (
	itemId INT NOT NULL,
	name VARCHAR(191) NOT NULL,
	type VARCHAR(191) NOT NULL,
	unit INT NOT NULL,
	PRIMARY KEY(itemId)
);

DROP TABLE IF EXISTS Stores;
CREATE TABLE Stores (
	needId INT NOT NULL AUTO_INCREMENT,
	itemId INT NOT NULL,
	name VARCHAR(191) NOT NULL,
	beneficiaryId INT NOT NULL,
	period VARCHAR(191) NOT NULL,
	urgency VARCHAR(191) NOT NULL,
	quantity VARCHAR(191) NOT NULL,
	PRIMARY KEY(needId)
);